name: Daily News Fetcher

on:
  schedule:
    - cron: "0 2 * * *"  # 每天 UTC 时间 2:00 执行，对应北京时间上午 10 点
  workflow_dispatch:     # 支持手动触发

jobs:
  update-news:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Run fetch_news.py
        run: python fetch_news.py

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add news.json
          git commit -m "🤖 Auto-update news.json from GitHub Actions" || echo "No changes to commit"
          git push