name: Update News

on:
  schedule:
    - cron: "0 7 * * *"  # 每天 UTC 7:00，对应美中时间凌晨 2:00
  workflow_dispatch:

jobs:
  update-news:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Run fetch script
        run: python fetch_news.py

      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add news.json
          git commit -m "Auto update news.json" || echo "No changes"
          git push
